[workspace]
git_release_enable = false

[[package]]
name = "whois42d-ng"
publish = false

[changelog]
tag_pattern = "v[0-9].*"
body = """
## [{{ version }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}

{% for commit in commits %}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
{% endfor %}

{% endfor %}
"""

commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->🚀 Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 3 -->♻️ Refactor" },
  { message = "^doc|^docs", group = "<!-- 4 -->📚 Documentation" },
  { message = "^test", group = "<!-- 5 -->✅ Testing" },
  { message = "^style", group = "<!-- 6 -->💄 Styling" },
  { message = "^ci", group = "<!-- 7 -->👷 CI" },
  { message = "^chore\\(release\\):", skip = true },
  { message = "^chore\\(deps.*\\)", skip = true },
  { message = "^chore", group = "<!-- 8 -->⚙️ Miscellaneous Tasks" },
  { message = "^revert", group = "<!-- 9 -->◀️ Revert" },
  { message = "^.*", group = "<!-- 10 -->💬 Other" },
]
