name: Release PR

on:
    push:
        branches: [master]

permissions:
    contents: write
    pull-requests: write

jobs:
    release-plz:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v7
              with:
                  fetch-depth: 0

            - name: Install Nix
              uses: cachix/install-nix-action@v31

            - name: Run release-plz
              run: nix run nixpkgs#release-plz -- release --git-token $GITHUB_TOKEN --forge github
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
